import { useSceneFrame } from "components/graphics/SceneRuntime";
import type { ThreeElements } from "@react-three/fiber";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";




type GLTFResult = ReturnType<typeof useGLTF> & {
  nodes: {
    ["buffer-0-mesh-0"]: THREE.Mesh;
    ["buffer-0-mesh-0_1"]: THREE.Mesh;
  };
  materials: {
    white: THREE.MeshStandardMaterial;
    black: THREE.MeshStandardMaterial;
  };
};

export default function Model(
  props: ThreeElements["group"] & { xDelta: number; yDelta: number }
) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/models/dice.glb") as GLTFResult;

  useSceneFrame((_, delta) => {
    if (group.current != null) {
      group.current.rotation.x += props.xDelta * 60 * Math.min(delta, 0.05);
      group.current.rotation.y += props.yDelta * 60 * Math.min(delta, 0.05);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[2.5, -0.81, -0.84]}>
        <mesh
          castShadow
          material={materials.white}
          geometry={nodes["buffer-0-mesh-0"].geometry}
        />
        <mesh
          castShadow
          material={materials.black}
          geometry={nodes["buffer-0-mesh-0_1"].geometry}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/dice.glb");
